torchrun --standalone --nnodes 1 --nproc-per-node 8 vla-scripts/finetune.py \
  --vla_path "openvla/openvla-7b" \
  --data_root_dir datasets/oxe_data \
  --dataset_name bridge \
  --run_root_dir checkpoints \
  --adapter_tmp_dir checkpoints/_tmp_adapter \
  --lora_rank 32 \
  --batch_size 12 \
  --grad_accumulation_steps 1 \
  --learning_rate 5e-4 \
  --image_aug True \
  --wandb_project OpenVLA \
  --wandb_entity fengg \
  --save_steps 10000