import argparse
import json
import os
import time
import warnings
import tqdm
import numpy as np
import cv2
import mediapy

import re
import tensorflow as tf
import tensorflow_datasets as tfds
from PIL import Image
from io import BytesIO
from utils import NumpyFloatValuesEncoder, post_process_caption

# Import Gemini
from google import genai
from google.genai import types

from prismatic.util.img_utils import draw_bboxes, name_to_random_color, resize_pos

# Configure Tensorflow with *no GPU devices* (to prevent clobber with PyTorch)
tf.config.set_visible_devices([], "GPU")

warnings.filterwarnings("ignore")

parser = argparse.ArgumentParser()

parser.add_argument("--id", type=int, default=0)
parser.add_argument("--splits", default=4, type=int)
parser.add_argument("--data_dir", type=str)
parser.add_argument("--dataset_name", type=str)
parser.add_argument("--model", type=str, default="gemini-2.0-flash", 
                   help="Gemini model to use, options: gemini-1.5-flash-latest, gemini-2.0-flash-lite, gemini-2.0-flash, gemini-2.5-pro-exp-03-25, gemini-2.5-pro-exp-03-25")
parser.add_argument("--visualize", default=False, action="store_true", help="Generate visualization videos of bounding boxes")
parser.add_argument("--bbox_json_path", type=str, help="Path to existing bounding box JSON file to visualize instead of generating new ones")
parser.add_argument("--output_video_dir", type=str, help="Directory to save visualization videos (defaults to results_path/videos/)")
parser.add_argument("--object_list_json_path", type=str, help="Path to object list JSON file generated by generate_object_list.py")
parser.add_argument("--enforce_consistency", default=True, action="store_true", help="Enforce consistent object naming and positioning across frames")

args = parser.parse_args()
result_path = f"./outputs/{args.dataset_name}/bboxes_gemini"
os.makedirs(result_path, exist_ok=True)
bbox_json_path = os.path.join(result_path, f"results_bboxes_{args.id}.json")

# If we're only visualizing an existing JSON file, we don't need to load the model
visualization_only_mode = args.bbox_json_path is not None and args.visualize

print("Loading data...")
split_percents = 100 // args.splits
start = args.id * split_percents
end = (args.id + 1) * split_percents

ds = tfds.load(args.dataset_name, data_dir=args.data_dir, split=f"train[{start}%:{end}%]")
print("Done.")

# Initialize Gemini client only if not in visualization-only mode
if not visualization_only_mode:
    GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
    if not GOOGLE_API_KEY:
        raise ValueError("GOOGLE_API_KEY environment variable is not set")

    client = genai.Client(api_key=GOOGLE_API_KEY)
    MODEL_ID = args.model
    print(f"Using Gemini model: {MODEL_ID}")

# Load existing bounding boxes if provided
existing_bbox_data = None
if args.bbox_json_path:
    print(f"Loading existing bounding boxes from {args.bbox_json_path}")
    try:
        with open(args.bbox_json_path, 'r') as f:
            existing_bbox_data = json.load(f)
        print(f"Successfully loaded bounding box data with {len(existing_bbox_data)} file entries")
    except Exception as e:
        print(f"Error loading bounding box data: {str(e)}")
        if not visualization_only_mode:
            print("Continuing with Gemini generation instead")
        else:
            raise ValueError("Failed to load bounding box data in visualization-only mode")

# Load object list and first frame bounding boxes if provided
object_list_data = None
if args.object_list_json_path is None:
    args.object_list_json_path = f"./outputs/{args.dataset_name}/object_lists_gemini/full_object_lists.json"
if args.object_list_json_path:
    print(f"Loading object list data from {args.object_list_json_path}")
    try:
        with open(args.object_list_json_path, 'r') as f:
            object_list_data = json.load(f)
        print(f"Successfully loaded object list data with {len(object_list_data)} file entries")
    except Exception as e:
        print(f"Error loading object list data: {str(e)}")

# System instructions for bounding box detection
bbox_format_instructions = """
[
  {
    "label": "object_name",
    "box": [y_min, x_min, y_max, x_max],
    "confidence": confidence_score
  },
  ... more objects ...
]

Where:
- [y_min, x_min, y_max, x_max] are STRICTLY normalized coordinates in the 0-1000 range (not 0-1!)
- (0,0) is the top-left corner and (1000,1000) is the bottom-right corner
- confidence_score is a value between 0 and 1, which is how confident the model is that the bounding box and object name are correct
- object_name is a descriptive label for the object
"""

bbox_guidelines = """
IMPORTANT GUIDELINES:
1. The box coordinates [y_min, x_min, y_max, x_max] MUST be normalized to a 0-1000 range (NOT 0-1!), where:
   - (0,0) is the top-left corner of the image
   - (1000,1000) is the bottom-right corner of the image
   - Example: [250, 300, 750, 800] means the box starts 25% down, 30% from left, extends to 75% down, 80% from left
2. Be as specific as possible when labeling objects (e.g., "plastic cup" instead of just "cup")
3. Detect manipulatable parts rather than just larger objects (e.g., "drawer handle" rather than just "drawer")
4. Always include the gripper in your detections
5. If the gripper is grasping an object, ensure both bounding boxes are properly detected
6. Pay attention to spatial relationships between objects and the gripper
"""

bounding_box_system_instructions = f"""
Return bounding boxes as a JSON array with the EXACT following format:
{bbox_format_instructions}

CRITICAL: All coordinates MUST be normalized to 0-1000 range, not 0-1 or pixel values.

Never return masks or code fencing. Limit to 25 objects.
If an object is present multiple times, name them according to their unique characteristic (colors, size, position, unique characteristics, etc.).

Always end your response with the word "FINISHED" on a new line to indicate you've completed the detection.
"""

safety_settings = [
    types.SafetySetting(
        category="HARM_CATEGORY_DANGEROUS_CONTENT",
        threshold="BLOCK_ONLY_HIGH",
    ),
]

def create_prompt_for_image(lang_instruction, prev_bboxes=None, object_list=None, first_frame_bboxes=None):
    """Create a prompt based on language instruction for object detection"""
    base_prompt = f"""
    Detect the 2d bounding boxes of all visible objects in the image, including the robotic gripper.
    
    Return ONLY a JSON array with objects in the following format:
    {bbox_format_instructions}
    
    {bbox_guidelines}
    """
    
    # Add consistency guidance if we have previous information
    consistency_guidance = ""
    
    # If we have an object list from generate_object_list.py, include it
    if object_list and len(object_list) > 0:
        object_list_str = ", ".join([f'"{obj}"' for obj in object_list])
        consistency_guidance += f"""
        IMPORTANT: Use EXACTLY these object names whenever they're visible in the scene: [{object_list_str}].
        Only add new object names if you detect something not in this list.
        """
    
    # If we have first frame bounding boxes, include them as reference
    if first_frame_bboxes and len(first_frame_bboxes) > 0:
        first_frame_guidance = """
        For reference, here are the objects detected in the first frame of this episode with their bounding boxes [y_min, x_min, y_max, x_max] (normalized to 0-1000):
        """
        
        for bbox in first_frame_bboxes:
            label = bbox["label"]
            box = bbox.get("normalized_box", bbox.get("box", [0, 0, 0, 0]))
            confidence = bbox.get("confidence", 0.95)
            
            # Convert box from [x_min, y_min, x_max, y_max] to [y_min, x_min, y_max, x_max] for VLM input
            x_min, y_min, x_max, y_max = box
            vlm_box = [y_min, x_min, y_max, x_max]
            first_frame_guidance += f"\n- {label}: {vlm_box} (confidence: {confidence})"
            
        consistency_guidance += first_frame_guidance
    
    # If we have previous frame bounding boxes, include them for temporal consistency
    if prev_bboxes and len(prev_bboxes) > 0:
        prev_frame_guidance = """
        For consistency with the previous frame, here are the objects detected in the previous frame with their bounding boxes [y_min, x_min, y_max, x_max] (normalized to 0-1000):
        """
        
        for bbox in prev_bboxes:
            prev_label = bbox[1]  # Label is the second element
            prev_box = bbox[3] if len(bbox) > 3 else None  # Normalized coordinates
            if prev_box:
                # Convert from [x_min, y_min, x_max, y_max] to [y_min, x_min, y_max, x_max] format for VLM
                x_min, y_min, x_max, y_max = prev_box
                vlm_box = [y_min, x_min, y_max, x_max]
                prev_frame_guidance += f"\n- {prev_label}: {vlm_box}"
            
        consistency_guidance += prev_frame_guidance + """
        
        IMPORTANT CONSISTENCY GUIDELINES:
        1. Use the SAME OBJECT NAMES as the previous frame whenever the same object is visible
        2. Bounding box positions should remain STABLE for stationary objects 
        3. Only adjust bounding boxes significantly if:
           - The object is being moved/manipulated by the gripper
           - The object has changed position in the scene
           - The camera perspective has changed
        4. Be sure to maintain bounding box accuracy for all visible objects
        """
    
    # Add task context if available
    if lang_instruction and len(lang_instruction.strip()) > 0:
        # Clean up instruction
        lang_instruction = lang_instruction.strip()
        if lang_instruction.endswith("."):
            lang_instruction = lang_instruction[:-1]
            
        # Create task-focused prompt
        task_prompt = f"""You're an expert vision system analyzing a robotic arm observation to complete this task: '{lang_instruction}'.

        Detect the 2d bounding boxes of all visible objects in the scene, paying special attention to:
        1. The robotic gripper (this MUST be detected)
        2. All objects relevant to the task: '{lang_instruction}'
        3. Any objects the gripper is currently interacting with
        4. Manipulatable parts of objects (handles, buttons, etc.)
        5. Any obstacles or objects in the environment that might affect task completion
        
        Return ONLY a JSON array with objects in the following format:
        {bbox_format_instructions}
        
        {bbox_guidelines}
        """
        
        # Add consistency guidance if available
        if consistency_guidance:
            task_prompt += "\n" + consistency_guidance
            
        return task_prompt
    
    # Add additional focus for the base prompt
    base_prompt += "\nFocus especially on tools, objects, robotic grippers, and any manipulatable parts."
    
    # Add consistency guidance if available
    if consistency_guidance:
        base_prompt += "\n" + consistency_guidance
        
    return base_prompt

def detect_bounding_boxes(image, prompt):
    """Use Gemini to detect bounding boxes in the image"""
    try:
        # Resize image to reasonable dimensions for the API
        img_resized = image.copy()
        original_width, original_height = image.size
        img_resized.thumbnail((512, 512), Image.Resampling.LANCZOS)
        
        # Call Gemini API
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=[prompt, img_resized],
            config=types.GenerateContentConfig(
                system_instruction=bounding_box_system_instructions,
                temperature=0.5,
                safety_settings=safety_settings,
            )
        )
        
        # Parse response
        try:
            text_response = response.text
            
            # Try several approaches to extract valid JSON
            formatted_bboxes = []
            
            # Approach 1: Try to find JSON using regex with proper nested bracket handling
            # This regex tries to find a JSON array with proper bracket nesting
            json_pattern = r'\[(?:[^[\]]*|\[(?:[^[\]]*|\[[^[\]]*\])*\])*\]'
            json_match = re.search(json_pattern, text_response.replace('\n', ' '))
            
            if json_match:
                try:
                    bboxes_json = json.loads(json_match.group(0))
                    # Process valid JSON results
                    for item in bboxes_json:
                        if "box" in item and "label" in item:
                            # Extract box coordinates
                            box = item["box"]
                            if isinstance(box, list) and len(box) == 4:
                                # Convert from Gemini format [y_min, x_min, y_max, x_max] to storage format [x_min, y_min, x_max, y_max]
                                y_min, x_min, y_max, x_max = box
                                
                                # Denormalize coordinates to pixel values
                                y1_px = int(y_min * original_height / 1000)
                                x1_px = int(x_min * original_width / 1000)
                                y2_px = int(y_max * original_height / 1000)
                                x2_px = int(x_max * original_width / 1000)
                                
                                # Get confidence if available or use default
                                conf = item.get("confidence", 0.95)
                                
                                # Store in [x_min, y_min, x_max, y_max] format for JSON storage
                                formatted_bboxes.append((conf, item["label"], [x1_px, y1_px, x2_px, y2_px]))
                            elif isinstance(box, dict) and all(k in box for k in ["x", "y", "width", "height"]):
                                # Handle old format if returned
                                # Normalize these values as well
                                x1 = int(box["x"] * original_width / 1000)
                                y1 = int(box["y"] * original_height / 1000)
                                x2 = x1 + int(box["width"] * original_width / 1000)
                                y2 = y1 + int(box["height"] * original_height / 1000)
                                
                                # Get confidence if available or use default
                                conf = item.get("confidence", 0.95)
                                
                                # Store in [x_min, y_min, x_max, y_max] format for JSON storage
                                formatted_bboxes.append((conf, item["label"], [x1, y1, x2, y2]))
                except json.JSONDecodeError:
                    # Approach 2: Try to fix common JSON errors before parsing
                    try:
                        potential_json = json_match.group(0)
                        # Replace common errors like missing commas between objects
                        corrected_json = re.sub(r'}\s*{', '},{', potential_json)
                        # Try parsing the corrected JSON
                        bboxes_json = json.loads(corrected_json)
                        # Process the JSON as before (same code as above)
                        for item in bboxes_json:
                            if "box" in item and "label" in item:
                                box = item["box"]
                                if isinstance(box, list) and len(box) == 4:
                                    # Convert from Gemini format [y_min, x_min, y_max, x_max] to storage format [x_min, y_min, x_max, y_max]
                                    y_min, x_min, y_max, x_max = box
                                    y1_px = int(y_min * original_height / 1000)
                                    x1_px = int(x_min * original_width / 1000)
                                    y2_px = int(y_max * original_height / 1000)
                                    x2_px = int(x_max * original_width / 1000)
                                    conf = item.get("confidence", 0.95)
                                    # Store in [x_min, y_min, x_max, y_max] format for JSON storage
                                    formatted_bboxes.append((conf, item["label"], [x1_px, y1_px, x2_px, y2_px]))
                                else:
                                    print(f"Warning: Unexpected box format: {box}")
                                    return []
                    except (json.JSONDecodeError, Exception) as e:
                        print(f"Second parsing attempt failed: {str(e)}")
            
            # If no bboxes were found after all attempts
            if not formatted_bboxes:
                print(f"Warning: Could not parse bounding box JSON from response. Response starts with: {text_response[:100]}...")
                    
            return formatted_bboxes
        except Exception as e:
            print(f"Error parsing Gemini response: {str(e)}")
            return []
            
    except Exception as e:
        print(f"Error calling Gemini API: {str(e)}")
        return []

def visualize_bboxes(image, bboxes, frame_idx=None):
    """Draw bounding boxes with labels and confidence scores on the image"""
    # Create a copy of the image to avoid modifying original
    vis_img = image.copy()
    
    # Convert bboxes from (confidence, label, bbox) format to dictionary format for draw_bboxes
    bboxes_dict = {}
    for confidence, label, bbox in bboxes:
        # Add confidence to label
        label_with_conf = f"{label}: {confidence:.2f}"
        bboxes_dict[label_with_conf] = bbox
    
    # Use draw_bboxes from prismatic.util.img_utils
    img_size = vis_img.shape[:2]
    vis_img = draw_bboxes(vis_img, bboxes_dict, img_size=img_size)
    
    # Add frame number if provided
    # if frame_idx is not None:
    #     cv2.putText(vis_img, f"Frame: {frame_idx}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
    
    return vis_img


bbox_results_json = {}
for ep_idx, episode in tqdm.tqdm(
    enumerate(ds),
    total=len(ds),
    desc=f"Generating bounding boxes [{start}%:{end}%]",
):

    episode_id = episode["episode_metadata"]["episode_id"].numpy()
    if isinstance(episode_id, bytes):
        episode_id = episode_id.decode()
    file_path = episode["episode_metadata"]["file_path"].numpy().decode()
    print(f"ID {args.id} starting ep: {episode_id}, {file_path}")

    if file_path not in bbox_results_json.keys():
        bbox_results_json[file_path] = {}

    start_time = time.time()
    bboxes_list = []
    
    # Initialize list to store visualization frames if enabled
    visualization_frames = [] if args.visualize else None
    
    # Extract language instruction from first step
    lang_instruction = ""
    current_step = next(iter(episode["steps"]), None)
    if current_step and "language_instruction" in current_step:
        lang_instruction = current_step["language_instruction"].numpy().decode()
    
    # Get object list and first frame bounding boxes from object_list_data if available
    object_list = None
    first_frame_bboxes = None
    if object_list_data and file_path in object_list_data and str(episode_id) in object_list_data[file_path]:
        episode_data = object_list_data[file_path][str(episode_id)]
        object_list = episode_data.get("object_list", [])
        first_frame_bboxes = episode_data.get("first_frame_bboxes", [])
        print(f"Using object list with {len(object_list)} objects and {len(first_frame_bboxes)} first frame bounding boxes")
    
    # Check if we can use existing bounding boxes for this episode
    using_existing_bboxes = False
    if existing_bbox_data and file_path in existing_bbox_data and str(ep_idx) in existing_bbox_data[file_path]:
        using_existing_bboxes = True
        print(f"Using existing bounding boxes for episode {episode_id}")
        bboxes_list = existing_bbox_data[file_path][str(ep_idx)]["bboxes"]
    
    prev_step_bboxes = None  # Track previous frame bboxes for consistency
    
    for step_idx, step in tqdm.tqdm(
        enumerate(episode["steps"]),
        total=len(episode["steps"]),
        desc=f"{'Visualizing' if using_existing_bboxes else 'Generating'} bounding boxes for Episode {episode_id}",
        leave=False,
    ):
        # Get image
        image = Image.fromarray(step["observation"]["image"].numpy())
        
        if using_existing_bboxes:
            # Use existing bounding boxes if available for this step
            if step_idx < len(bboxes_list):
                bboxes = bboxes_list[step_idx]
            else:
                print(f"Warning: Missing bounding box data for step {step_idx}")
                bboxes = []
        else:
            # Create prompt based on language instruction and consistency information
            prompt = create_prompt_for_image(
                lang_instruction, 
                prev_bboxes=prev_step_bboxes, 
                object_list=object_list,
                first_frame_bboxes=first_frame_bboxes
            )
            
            # Detect bounding boxes using Gemini
            for _ in range(3):
                bboxes = detect_bounding_boxes(image, prompt)
                if len(bboxes) > 0:
                    break
                else:
                    print("Failed to detect bounding boxes. Retrying...")
            
            # Save current bboxes for next frame's consistency
            if args.enforce_consistency:
                prev_step_bboxes = bboxes
                
            # Add to results
            bboxes_list.append(bboxes)
        
        # Create visualization if enabled
        if args.visualize:
            # Convert PIL image to numpy for OpenCV processing
            img_array = np.array(image)
            # Draw bounding boxes on the image
            vis_frame = visualize_bboxes(img_array, bboxes, frame_idx=step_idx)
            visualization_frames.append(vis_frame)
    
    end_time = time.time()
    
    # Only update the results JSON if we're not just visualizing
    if not using_existing_bboxes:
        bbox_results_json[file_path][str(ep_idx)] = {
            "episode_id": str(episode_id),
            "file_path": file_path,
            "bboxes": bboxes_list,
        }

        # Save results after each episode
        with open(bbox_json_path, "w") as f:
            json.dump(bbox_results_json, f, cls=NumpyFloatValuesEncoder)
    
    print(f"ID {args.id} finished ep ({ep_idx} / {len(ds)}). Elapsed time: {round(end_time - start_time, 2)}")

    # Save visualization video if enabled
    if args.visualize and visualization_frames:
        # Use custom output directory if provided, otherwise use default
        video_dir = args.output_video_dir if args.output_video_dir else f"{result_path}/videos/{args.id}"
        os.makedirs(video_dir, exist_ok=True)
        video_path = f"{video_dir}/episode_{episode_id}.mp4"
        mediapy.write_video(video_path, visualization_frames, fps=10)
        print(f"Saved visualization video to {video_path}")
